ARG UBUNTU_RELEASE=24.04
ARG BASE_IMAGE=ubuntu/jre:17_edge
ARG MAVEN_IMAGE=maven:3.9.9-eclipse-temurin-17
ARG ARCH=amd64
FROM $MAVEN_IMAGE AS builder
FROM ubuntu:26.04 AS jdk
ARG ARCH
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
        ca-certificates-java \
        binutils \
        openjdk-17-jdk \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN /usr/lib/jvm/java-17-openjdk-$ARCH/bin/jlink --no-header-files --no-man-pages --strip-debug \
    --add-modules ALL-MODULE-PATH --output /opt/java

FROM $BASE_IMAGE
ARG ARCH

COPY --from=builder /bin/sh /bin/sh
COPY --from=builder /usr/bin/chmod /usr/bin/chmod
COPY --from=builder /usr/bin/uname /usr/bin/uname
COPY --from=builder /usr/bin/dirname /usr/bin/dirname
COPY --from=builder /usr/bin/grep /usr/bin/grep
# note, Temurin base does not install into /etc/maven and /usr/share/java
# other base might require copying those folders
COPY --from=builder /usr/share/maven /usr/share/maven

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-$ARCH

# Add javac compiler for maven (it always recompiles package-info.java)
COPY --from=jdk /opt/java/bin/javac  /usr/lib/jvm/java-17-openjdk-$ARCH/bin
# compatibility signatures
COPY --from=jdk /opt/java/lib/ct.sym /usr/lib/jvm/java-17-openjdk-$ARCH/lib
# additional jars
COPY --from=jdk /opt/java/lib/*.jar  /usr/lib/jvm/java-17-openjdk-$ARCH/lib
# copy modules
COPY --from=jdk /opt/java/lib/modules /usr/lib/jvm/java-17-openjdk-$ARCH/lib

ENTRYPOINT [ "/usr/share/maven/bin/mvn" ]
