#!/bin/bash
set -ex

echo "Running test for HTTPS connection app"

javac src/Main.java -d .

# run the test and if it fails, retry with the full network diagnostics
docker run --rm -v $PWD:/app:ro \
    -w /app $BASE_IMAGE exec java -cp /app Main || \
    docker run --rm -v $PWD:/app:ro \
    -w /app $BASE_IMAGE exec java -cp /app -Djavax.net.debug=all Main
