name: "Chiselled Ubuntu 'jre' Tests"

on:
  pull_request:
  push:

env:
  image-name: ubuntu/jre:test
  build-image-name: ubuntu/jre:test-builder
  maven-image-name: ubuntu/jre:test-maven
  maven-image-base: maven:3.9-eclipse-temurin-25

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        ubuntu-release: ["24.04"]
        arch: ["amd64"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '25'

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 6/stable

      - name: Setup rockcraft
        run: |
          rm -rf /home/runner/.local/state/rockcraft/log/*
          sudo snap remove rockcraft || true
          sudo snap install rockcraft --classic --channel=edge

      - name: Update apt
        run: |
          sudo apt-get update

      - name: Setup yamllint
        run: |
          sudo apt-get install -y yamllint

      - name: Lint rockcraft.yaml
        run: |
          yamllint ./jre/ubuntu-26.04-headless/rockcraft.yaml

      - name: Run Tests
        working-directory: jre/ubuntu-26.04-headless
        run: |
          rockcraft test

  multi-arch-build:
    runs-on: ubuntu-24.04
    name: Multi Architecture Build
    strategy:
      fail-fast: false
      matrix:
        ubuntu-release: ["24.04"]
        arch: ["amd64", "arm64"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 6/stable

      - name: Setup rockcraft
        run: |
          rm -rf /home/runner/.local/state/rockcraft/log/*
          sudo snap remove rockcraft || true
          sudo snap install rockcraft --classic --channel edge

      - name: Build the jre image
        working-directory: jre/ubuntu-26.04-headless
        run: |
          rockcraft pack
