name: "Chiselled Ubuntu 'jre' Tests"

on:
  pull_request:
  push:

env:
  image-name: ubuntu/jre:test
  build-image-name: ubuntu/jre:test-builder
  maven-image-name: ubuntu/jre:test-maven
  maven-image-base: maven:3.9.9-eclipse-temurin-21

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        ubuntu-release: ["24.04"]
        arch: ["amd64"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/candidate

      - name: Setup rockcraft
        run: |
          rm -rf /home/runner/.local/state/rockcraft/log/*
          snap remove rockcraft || true
          snap install rockcraft --classic

      - name: Setup yamllint
        run: |
          apt-get install -U -y yamllint

      - name: Lint rockcraft.yaml
        run: |
          find . -name rockcraft.yaml -exec yamllint {} \;


      - name: Tests Maven cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Tests Petclinic
        uses: actions/cache@v4
        with:
          path: tests/petclinic-test/spring-petclinic
          key: tests-petclinic-test-spring-petclinic
          restore-keys: |
            tests-petclinic-test-spring-petclinic

      - name: Build Test images
        run: |
          ./tests/build-test-images.sh ${{ matrix.arch }} \
            ${{ env.image-name }} \
            ${{ env.build-image-name }} \
            ${{ env.maven-image-name }} \
            ${{ env.maven-image-base }} \
            ${{ matrix.ubuntu-release }}

      - name: Run Tests
        working-directory: ${{ github.workspace }}/tests/
        run: |
          ./run-all-tests ${{ env.image-name }} \
                          ${{ env.build-image-name }} \
                          ${{ runner.temp }}/.m2 \
                          ${{ env.maven-image-name }}
  multi-arch-build:
    runs-on: ubuntu-24.04
    name: Multi Architecture Build
    strategy:
      fail-fast: false
      matrix:
        ubuntu-release: ["24.04"]
        arch: ["amd64", "arm64"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/candidate

      - name: Setup rockcraft
        run: |
          rm -rf /home/runner/.local/state/rockcraft/log/*
          snap remove rockcraft || true
          snap install rockcraft --classic
          sudo apt install yamllint

      - name: Build the jre image
        run: |
          cd jre/ubuntu-24.04-headless
          rockcraft pack
